### ISSUE TITLE
No service exception when using DependencyInjection 

### ISSUE THREAD

**Issue by mmarkwort** [whyseco/graphql-schema-declare#7]
I use `ObjectGraphTypeExtensions.ServiceProvider = app.ApplicationServices;` to use DependencyInjection.

I got an exception when I call `this.Query<TestController>(c => c.Test(default))`:

```
No service for type 'GraphQL.SchemaDeclare.GenerationServices.ExpressionToFieldTypeGenerator' has been registered.
```

When I add manually the service

```
services.AddSingleton<GraphQL.SchemaDeclare.GenerationServices.ExpressionToFieldTypeGenerator>();
```
the exception is gone.

Do I something wrong or is the call just missing in `AddGraphQLSchemaDeclareService()`?

**Comment by kYann** [comment]
Thanks ! Should be fine in this version [https://www.nuget.org/packages/GraphQL.SchemaDeclare/2.0.1](https://www.nuget.org/packages/GraphQL.SchemaDeclare/2.0.1)

(Our DI framework does not need to register concrete type so we did not have the issue)

**Comment by mmarkwort** [comment]
Ok, thank you.
